<<<<<<< HEAD
spring:
  datasource:
    url: jdbc:mysql://krasvbank.cbo8ks6iutwr.eu-north-1.rds.amazonaws.com/krasvbank
    username: root
    password: manager123
    driver-class-name: com.mysql.cj.jdbc.Driver
    init.mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
=======
spring:
  datasource:
    url: jdbc:mysql://krasvbank.cbo8ks6iutwr.eu-north-1.rds.amazonaws.com/krasvbank
    username: root
    password: manager123
    driver-class-name: com.mysql.cj.jdbc.Driver
    init.mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
>>>>>>> 1f121701983e37c5f071e9c7568ecab8f131e0af
    